/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Abcs;

import java.sql.ResultSet;
import java.sql.SQLException;

import javax.swing.JMenuBar;
import javax.swing.JOptionPane;

/**
 *
 * @author jossu
 */
public class Agenda extends javax.swing.JFrame {

    /**
     * Creates new form Agenda
     */
    private BarraMenu menu = new BarraMenu();
    private JMenuBar menuBar = menu.getMenu();
    private Persona persona = new Persona();
    AdministradorBD conectorBD = new AdministradorBD();
    public Agenda() {
        initComponents();
        this.setJMenuBar(menuBar);
        conectorBD.conectar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nombre_TextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        telefono_TextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        correo_TextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cum_TextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        empresa_TextField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        boton_Agregar = new javax.swing.JButton();
        boton_Modificar = new javax.swing.JButton();
        boton_Buscar = new javax.swing.JButton();
        boton_Borrar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        grupo_TextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre");

        jLabel2.setText("Telefono");

        jLabel3.setText("Correo Electronico");

        jLabel4.setText("Cumpleaños");

        jLabel5.setText("Empresa");

        boton_Agregar.setText("Agregar");
        boton_Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_AgregarActionPerformed(evt);
            }
        });
        jPanel1.add(boton_Agregar);

        boton_Modificar.setText("Modificar");
        boton_Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_ModificarActionPerformed(evt);
            }
        });
        jPanel1.add(boton_Modificar);

        boton_Buscar.setText("Buscar");
        boton_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_BuscarActionPerformed(evt);
            }
        });
        jPanel1.add(boton_Buscar);

        boton_Borrar.setText("Eliminar");
        boton_Borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_BorrarActionPerformed(evt);
            }
        });
        jPanel1.add(boton_Borrar);

        jLabel6.setText("Grupo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1)
                        .addComponent(nombre_TextField)
                        .addComponent(telefono_TextField)
                        .addComponent(correo_TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(empresa_TextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                        .addComponent(cum_TextField, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(grupo_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombre_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(telefono_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(correo_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cum_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(empresa_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(grupo_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_AgregarActionPerformed
        // TODO add your handling code here:
        String consulta = "INSERT INTO Contactos (nombre, telefono, correo, cumpleaños, empresa,grupo) VALUES " 
        + "(?, ?, ?, ?, ?,?)";
        persona.setNombre(nombre_TextField.getText());
        persona.setTelefono(telefono_TextField.getText());
        persona.setCorreo(correo_TextField.getText());
        try{
            conectorBD.ejecutarConsulta(consulta, persona.getNombre(), persona.getTelefono(), persona.getCorreo(), cum_TextField.getText(), empresa_TextField.getText(),grupo_TextField.getText());

        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "Error al agregar el contacto" + ex.toString());
        }


    }//GEN-LAST:event_boton_AgregarActionPerformed

    private void boton_ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_ModificarActionPerformed
        // TODO add your handling code here:
        String consulta ="UPDATE Contactos SET telefono = ?, correo = ?, cumpleaños = ?, empresa = ?, grupo = ? WHERE nombre = ?";
        try{
            conectorBD.ejecutarConsulta(consulta, telefono_TextField.getText(), correo_TextField.getText(), cum_TextField.getText(), empresa_TextField.getText(), grupo_TextField.getText(), nombre_TextField.getText());
            JOptionPane.showMessageDialog(null, "Contacto modificado");
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "Error al modificar el contacto" + ex.toString());
        }
    }//GEN-LAST:event_boton_ModificarActionPerformed

    private void boton_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_BuscarActionPerformed
        try (// TODO add your handling code here:
		ResultSet rs = conectorBD.hacerBusqueda("Contactos","nombre", nombre_TextField.getText())) {
		if(rs.next()){
                    telefono_TextField.setText(rs.getString("telefono"));
                    correo_TextField.setText(rs.getString("correo"));
                    cum_TextField.setText(rs.getString("cumpleaños"));
                    empresa_TextField.setText(rs.getString("empresa"));
                    grupo_TextField.setText(rs.getString("grupo"));
        }
        } catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    }//GEN-LAST:event_boton_BuscarActionPerformed

    private void boton_BorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_BorrarActionPerformed
        // TODO add your handling code here:
        String consulta = "DELETE FROM Contactos WHERE nombre = ?";
        try{
            conectorBD.ejecutarConsulta(consulta, nombre_TextField.getText());
            JOptionPane.showMessageDialog(null, "Contacto eliminado");
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "Error al eliminar el contacto" + ex.toString());
        }
    }//GEN-LAST:event_boton_BorrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_Agregar;
    private javax.swing.JButton boton_Borrar;
    private javax.swing.JButton boton_Buscar;
    private javax.swing.JButton boton_Modificar;
    private javax.swing.JTextField correo_TextField;
    private javax.swing.JTextField cum_TextField;
    private javax.swing.JTextField empresa_TextField;
    private javax.swing.JTextField grupo_TextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nombre_TextField;
    private javax.swing.JTextField telefono_TextField;
    // End of variables declaration//GEN-END:variables
}
