/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Abcs;

/**
 *
 * @author jossu
 */
public class Biblioteca extends javax.swing.JFrame {

    /**
     * Creates new form Biblioteca
     */
    public Biblioteca() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        codigo_TextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        titulo_TextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        autor_TextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        editorial_Textfield = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lanzamiento_TextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Generos_TextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        paginas_TextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        boton_Anterior = new javax.swing.JButton();
        boton_Siguiente = new javax.swing.JButton();
        boton_Buscar = new javax.swing.JButton();
        boton_Agregar = new javax.swing.JButton();
        boton_Modificar = new javax.swing.JButton();
        boton_Eliminar = new javax.swing.JButton();
        boton_Regresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Codigo:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 19, -1, -1));
        getContentPane().add(codigo_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 16, 149, -1));

        jLabel2.setText("Titulo:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 65, -1, -1));
        getContentPane().add(titulo_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 87, 188, -1));

        jLabel3.setText("Autor:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 65, -1, -1));
        getContentPane().add(autor_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 87, 166, -1));

        jLabel4.setText("Editorial");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 127, -1, -1));
        getContentPane().add(editorial_Textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 149, 188, -1));

        jLabel5.setText("Fecha de Lanzamiento");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 127, -1, -1));
        getContentPane().add(lanzamiento_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 149, 166, -1));

        jLabel6.setText("Generos");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 191, -1, -1));
        getContentPane().add(Generos_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 213, 188, -1));

        jLabel7.setText("Paginas");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 191, -1, -1));
        getContentPane().add(paginas_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 213, 166, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, -1, 243));

        jLabel8.setText("Sinopsis");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, -1, -1));

        boton_Anterior.setText("<--Anterior");
        jPanel1.add(boton_Anterior);

        boton_Siguiente.setText("Siguiente-->");
        jPanel1.add(boton_Siguiente);

        boton_Buscar.setText("Buscar");
        jPanel1.add(boton_Buscar);

        boton_Agregar.setText("Agregar");
        jPanel1.add(boton_Agregar);

        boton_Modificar.setText("Modificiar");
        jPanel1.add(boton_Modificar);

        boton_Eliminar.setText("Eliminar");
        jPanel1.add(boton_Eliminar);

        boton_Regresar.setText("Regresar");
        jPanel1.add(boton_Regresar);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 750, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Biblioteca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Generos_TextField;
    private javax.swing.JTextField autor_TextField;
    private javax.swing.JButton boton_Agregar;
    private javax.swing.JButton boton_Anterior;
    private javax.swing.JButton boton_Buscar;
    private javax.swing.JButton boton_Eliminar;
    private javax.swing.JButton boton_Modificar;
    private javax.swing.JButton boton_Regresar;
    private javax.swing.JButton boton_Siguiente;
    private javax.swing.JTextField codigo_TextField;
    private javax.swing.JTextField editorial_Textfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField lanzamiento_TextField;
    private javax.swing.JTextField paginas_TextField;
    private javax.swing.JTextField titulo_TextField;
    // End of variables declaration//GEN-END:variables
}
