/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Abcs;

/**
 *
 * @author jossu
 */
public class Hospitall extends javax.swing.JFrame {

    /**
     * Creates new form Hospitall
     */
    public Hospitall() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        boton_AgregarPaciente = new javax.swing.JButton();
        boton_BuscarPaciente = new javax.swing.JButton();
        boton_Eliminar = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        nombre_TextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tipoSangre_TextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        peso_TextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        altura_TextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        contacto_TextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        nacionalida_TextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        edad_TextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        estado_TextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();

        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boton_AgregarPaciente.setText("Agregar");
        jPanel1.add(boton_AgregarPaciente);

        boton_BuscarPaciente.setText("Buscar");
        jPanel1.add(boton_BuscarPaciente);

        boton_Eliminar.setText("Eliminar");
        jPanel1.add(boton_Eliminar);

        jButton4.setText("<--Anterior");
        jPanel1.add(jButton4);

        jButton5.setText("Siguiente-->");
        jPanel1.add(jButton5);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 406, 620, 45));

        jLabel1.setText("Nombre:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 52, -1, -1));
        getContentPane().add(nombre_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 49, 170, -1));

        jLabel2.setText("Grupo Sanguíneo:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 86, -1, -1));
        getContentPane().add(tipoSangre_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 83, 93, -1));

        jLabel3.setText("Peso:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 126, -1, -1));
        getContentPane().add(peso_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 123, 84, -1));

        jLabel4.setText("Altura:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 151, -1, -1));
        getContentPane().add(altura_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 151, 83, -1));

        jLabel5.setText("Contacto De Emergencia:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 366, -1, -1));
        getContentPane().add(contacto_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 366, 166, -1));

        jLabel6.setText("Genero:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 185, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 207, 41, -1));

        jLabel7.setText("Nacionalidad:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 235, -1, -1));
        getContentPane().add(nacionalida_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 257, 144, -1));

        jLabel9.setText("Edad:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 291, -1, -1));
        getContentPane().add(edad_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 313, 60, -1));

        jLabel10.setText("Estado Civil:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 126, -1, -1));
        getContentPane().add(estado_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 151, 112, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 114, -1, 240));

        jLabel11.setText("Historial Medico");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 86, 208, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hospitall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hospitall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hospitall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hospitall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hospitall().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField altura_TextField;
    private javax.swing.JButton boton_AgregarPaciente;
    private javax.swing.JButton boton_BuscarPaciente;
    private javax.swing.JButton boton_Eliminar;
    private javax.swing.JTextField contacto_TextField;
    private javax.swing.JTextField edad_TextField;
    private javax.swing.JTextField estado_TextField;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField nacionalida_TextField;
    private javax.swing.JTextField nombre_TextField;
    private javax.swing.JTextField peso_TextField;
    private javax.swing.JTextField tipoSangre_TextField;
    // End of variables declaration//GEN-END:variables
}
