/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Abcs;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import javax.swing.JOptionPane;

/**
 *
 * @author jossu
 */
public class Hospitall extends javax.swing.JFrame {

    /**
     * Creates new form Hospitall
     */
    private Paciente paciente = new Paciente();
    private List<Paciente> pacientes = new ArrayList<Paciente>();
    private AdministradorBD conectorBD = new AdministradorBD();
    public Hospitall() {
        initComponents();
        conectorBD.conectar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        boton_AgregarPaciente = new javax.swing.JButton();
        boton_BuscarPaciente = new javax.swing.JButton();
        boton_Eliminar = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        nombre_TextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tipoSangre_TextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        peso_TextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        altura_TextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        telefono_TextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        genero_TextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        nacionalida_TextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        edad_TextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        estado_TextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        antecedentes_TextArea = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        alergias_TextField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        enfermedades_TextField = new javax.swing.JTextField();
        boton_Pruebas = new javax.swing.JButton();

        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        boton_AgregarPaciente.setText("Agregar");
        boton_AgregarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_AgregarPacienteActionPerformed(evt);
            }
        });
        jPanel1.add(boton_AgregarPaciente);

        boton_BuscarPaciente.setText("Buscar");
        boton_BuscarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_BuscarPacienteActionPerformed(evt);
            }
        });
        jPanel1.add(boton_BuscarPaciente);

        boton_Eliminar.setText("Eliminar");
        boton_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_EliminarActionPerformed(evt);
            }
        });
        jPanel1.add(boton_Eliminar);

        jButton4.setText("<--Anterior");
        jPanel1.add(jButton4);

        jButton5.setText("Siguiente-->");
        jPanel1.add(jButton5);

        jLabel1.setText("Nombre:");

        jLabel2.setText("Grupo Sanguíneo:");

        jLabel3.setText("Peso:");

        jLabel4.setText("Altura:");

        jLabel5.setText("Contacto De Emergencia:");

        jLabel6.setText("Genero:");

        jLabel7.setText("Nacionalidad:");

        jLabel9.setText("Edad:");

        jLabel10.setText("Estado Civil:");

        antecedentes_TextArea.setColumns(20);
        antecedentes_TextArea.setRows(5);
        jScrollPane1.setViewportView(antecedentes_TextArea);

        jLabel11.setText("Historial Medico");

        jLabel12.setText("Alergias");

        jLabel13.setText("Enfermedades");

        boton_Pruebas.setText("Pruebas");
        boton_Pruebas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_PruebasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(12, 12, 12)
                .addComponent(telefono_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(12, 12, 12)
                        .addComponent(tipoSangre_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(212, 212, 212)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(12, 12, 12)
                                .addComponent(peso_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(jLabel10))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(6, 6, 6)
                                .addComponent(altura_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(estado_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(23, 23, 23)
                                .addComponent(jLabel12))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(genero_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)
                                .addComponent(alergias_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(91, 91, 91)
                                .addComponent(jLabel13))
                            .addComponent(jLabel9)
                            .addComponent(edad_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nacionalida_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(enfermedades_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(nombre_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(boton_Pruebas)
                        .addGap(151, 151, 151))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel1))
                            .addComponent(nombre_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(boton_Pruebas)))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tipoSangre_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel11))))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(peso_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel10))))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(altura_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(estado_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel12)))
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(genero_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(alergias_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel13)))
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nacionalida_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(enfermedades_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addComponent(jLabel9)
                        .addGap(6, 6, 6)
                        .addComponent(edad_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(telefono_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_AgregarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_AgregarPacienteActionPerformed
        // TODO add your handling code here:
        paciente.setNombre(nombre_TextField.getText());
        paciente.setSexo(genero_TextField.getText());
        paciente.setEstadoCivil(estado_TextField.getText());
        paciente.setTelefono(telefono_TextField.getText());
        paciente.setTipoSangre(tipoSangre_TextField.getText());
        paciente.setAlergias(alergias_TextField.getText());
        paciente.setEnfermedades(enfermedades_TextField.getText());
        paciente.setAntecedentes(antecedentes_TextArea.getText());
        paciente.setEstatura(altura_TextField.getText());
        paciente.setPeso(peso_TextField.getText());
        try {
            conectorBD.ejecutarConsulta("INSERT INTO Pacientes (nombre, edad, genero, nacionalidad, estadoCivil, telefono, tipoSangre, alergias, enfermedades, antecedentes, peso, altura)"
                    + "VALUES (?,?,?,?,?,?,?,?,?,?,?,?)", paciente.getNombre(),paciente.getEdad(),paciente.getSexo(),paciente.getNacionalidad(),paciente.getEstadoCivil()
                    ,paciente.getTelefono(),paciente.getTipoSangre(),paciente.getAlergias(),paciente.getEnfermedades(),paciente.getAntecedentes(),paciente.getPeso(),paciente.getEstatura());
            JOptionPane.showMessageDialog(null, "Paciente agregado correctamente.");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al insertar empleado en la base de datos:\n" + ex.toString());
        }
    }//GEN-LAST:event_boton_AgregarPacienteActionPerformed

    private void boton_PruebasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_PruebasActionPerformed
        // TODO add your handling code here:
        nombre_TextField.setText("Juan");
        edad_TextField.setText("20");
        genero_TextField.setText("Masculino");
        nacionalida_TextField.setText("Mexicano");
        estado_TextField.setText("Soltero");
        telefono_TextField.setText("1234567890");
        tipoSangre_TextField.setText("O+");
        alergias_TextField.setText("Ninguna");
        enfermedades_TextField.setText("Ninguna");
        antecedentes_TextArea.setText("Ninguno");
        peso_TextField.setText("70");
        altura_TextField.setText("1.70");
        
    }//GEN-LAST:event_boton_PruebasActionPerformed

    private void boton_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_EliminarActionPerformed
        // TODO add your handling code here:
        try {
            conectorBD.ejecutarConsulta("DELETE FROM Pacientes WHERE nombre = ?", nombre_TextField.getText());
            JOptionPane.showMessageDialog(null, "Paciente eliminado correctamente.");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al eliminar empleado en la base de datos:\n" + ex.toString());
        }
        
    }//GEN-LAST:event_boton_EliminarActionPerformed

    private void boton_BuscarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_BuscarPacienteActionPerformed
        try (// TODO add your handling code here:
        ResultSet rs = conectorBD.hacerBusqueda("Pacientes", "nombre",nombre_TextField.getText())) {
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al buscar paciente en la base de datos:\n" + e.toString());
        }
    }//GEN-LAST:event_boton_BuscarPacienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hospitall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hospitall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hospitall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hospitall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hospitall().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alergias_TextField;
    private javax.swing.JTextField altura_TextField;
    private javax.swing.JTextArea antecedentes_TextArea;
    private javax.swing.JButton boton_AgregarPaciente;
    private javax.swing.JButton boton_BuscarPaciente;
    private javax.swing.JButton boton_Eliminar;
    private javax.swing.JButton boton_Pruebas;
    private javax.swing.JTextField edad_TextField;
    private javax.swing.JTextField enfermedades_TextField;
    private javax.swing.JTextField estado_TextField;
    private javax.swing.JTextField genero_TextField;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nacionalida_TextField;
    private javax.swing.JTextField nombre_TextField;
    private javax.swing.JTextField peso_TextField;
    private javax.swing.JTextField telefono_TextField;
    private javax.swing.JTextField tipoSangre_TextField;
    // End of variables declaration//GEN-END:variables
}
