/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Abcs;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JMenuBar;
import javax.swing.JOptionPane;

/**
 *
 * @author jossu
 */
public class Inventario extends javax.swing.JFrame {

    /**
     * Creates new form Inventario
     */
    private BarraMenu menu = new BarraMenu();
    private JMenuBar menuBar = menu.getMenu();
    private AdministradorBD conectorBD = new AdministradorBD();
    public Inventario() {
        initComponents();
        conectorBD.conectar();
        this.setJMenuBar(menuBar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        clave_TextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nombre_TextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        precio_TextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cantidad_TextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        proveedor_TextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        boton_Buscar = new javax.swing.JButton();
        boton_AgregarCantidad = new javax.swing.JButton();
        boton_SacarCantidad = new javax.swing.JButton();
        boton_EliminarProducto = new javax.swing.JButton();
        boton_Agregar_Producto = new javax.swing.JButton();
        boton_Modificar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        existencias_TextField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        descripcion_TextArea = new javax.swing.JTextArea();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Clave del Producto");

        jLabel2.setText("Nombre Producto");

        jLabel3.setText("Precio");

        jLabel4.setText("Cantidad");

        jLabel5.setText("Proveedor");

        jLabel6.setText("Descripcion");

        boton_Buscar.setText("Buscar Producto");
        boton_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_BuscarActionPerformed(evt);
            }
        });
        jPanel1.add(boton_Buscar);

        boton_AgregarCantidad.setText("Agregar Cantidad");
        boton_AgregarCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_AgregarCantidadActionPerformed(evt);
            }
        });
        jPanel1.add(boton_AgregarCantidad);

        boton_SacarCantidad.setText("Sacar Cantidad");
        boton_SacarCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_SacarCantidadActionPerformed(evt);
            }
        });
        jPanel1.add(boton_SacarCantidad);

        boton_EliminarProducto.setText("Eliminar Producto");
        boton_EliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_EliminarProductoActionPerformed(evt);
            }
        });
        jPanel1.add(boton_EliminarProducto);

        boton_Agregar_Producto.setText("Agregar Producto");
        boton_Agregar_Producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_Agregar_ProductoActionPerformed(evt);
            }
        });
        jPanel1.add(boton_Agregar_Producto);

        boton_Modificar.setText("Modificar");
        boton_Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_ModificarActionPerformed(evt);
            }
        });
        jPanel1.add(boton_Modificar);

        jLabel7.setText("Existencias");

        existencias_TextField.setEditable(false);

        descripcion_TextArea.setColumns(20);
        descripcion_TextArea.setRows(5);
        jScrollPane2.setViewportView(descripcion_TextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(clave_TextField))
                            .addComponent(jLabel3)
                            .addComponent(existencias_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(precio_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(nombre_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cantidad_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(proveedor_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clave_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombre_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(precio_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cantidad_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(proveedor_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(existencias_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_BuscarActionPerformed

        try{
            ResultSet rs = conectorBD.hacerBusqueda("Productos", "id", clave_TextField.getText());
            if(rs.next()){
                nombre_TextField.setText(rs.getString("nombre"));
                precio_TextField.setText(rs.getString("precio"));
                proveedor_TextField.setText(rs.getString("proveedor"));
                descripcion_TextArea.setText(rs.getString("descripcion"));
                existencias_TextField.setText(rs.getString("existencias"));
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error al buscar el producto");
        }

    }//GEN-LAST:event_boton_BuscarActionPerformed

    private void boton_AgregarCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_AgregarCantidadActionPerformed
        // TODO add your handling code here:
        try {
            String productoId = clave_TextField.getText();
            int cantidadIngresada = Integer.parseInt(cantidad_TextField.getText());
        
            // Realizar búsqueda del producto por su ID
            ResultSet rs = conectorBD.hacerBusqueda("Productos", "id", productoId);
            if (rs.next()) {
                int existenciasActuales = rs.getInt("existencias");
                int existenciasNuevas = existenciasActuales + cantidadIngresada;
                // Actualizar las existencias del producto en la base de datos
                String consulta = "UPDATE Productos SET existencias = ? WHERE id = ?";
                conectorBD.ejecutarConsulta(consulta, existenciasNuevas, productoId);
                JOptionPane.showMessageDialog(null, "Existencias agregadas");
                conectorBD.vaciarCampos(clave_TextField, cantidad_TextField);
            } else {
                JOptionPane.showMessageDialog(null, "No se encontró el producto");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al agregar existencias: " + e.toString());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Cantidad inválida");
        }
        
        
    }//GEN-LAST:event_boton_AgregarCantidadActionPerformed

    private void boton_Agregar_ProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_Agregar_ProductoActionPerformed
        // TODO add your handling code here:
        String consulta = "INSERT INTO Productos (id,nombre,precio,proveedor,descripcion,existencias) VALUES (?,?,?,?,?,?)";
        try {
            ResultSet rs = conectorBD.hacerBusqueda("Productos","existencias", clave_TextField.getText());
            conectorBD.ejecutarConsulta(consulta, clave_TextField.getText(),nombre_TextField.getText(),precio_TextField.getText(),
            proveedor_TextField.getText(),descripcion_TextArea.getText(),cantidad_TextField.getText());

            if(rs.next()){
                existencias_TextField.setText(rs.getString("existencias"));
            }
            JOptionPane.showMessageDialog(null, "Producto agregado");

        } catch (SQLException e) {
            // TODO Auto-generated catch block
            JOptionPane.showMessageDialog(null, e.toString());
        };
    }//GEN-LAST:event_boton_Agregar_ProductoActionPerformed

    private void boton_SacarCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_SacarCantidadActionPerformed
        // TODO add your handling code here:
        try {
            String productoId = clave_TextField.getText();
            int cantidadIngresada = Integer.parseInt(cantidad_TextField.getText());
        
            // Realizar búsqueda del producto por su ID
            ResultSet rs = conectorBD.hacerBusqueda("Productos", "id", productoId);
            if (rs.next()) {
                int existenciasActuales = rs.getInt("existencias");
                
                if (existenciasActuales >= cantidadIngresada) {
                    int existenciasNuevas = existenciasActuales - cantidadIngresada;
        
                    // Actualizar las existencias del producto en la base de datos
                    String consulta = "UPDATE Productos SET existencias = ? WHERE id = ?";
                    conectorBD.ejecutarConsulta(consulta, existenciasNuevas, productoId);
        
                    // Mostrar mensaje de éxito y vaciar los campos de texto
                    JOptionPane.showMessageDialog(null, "Existencias restadas");
                    conectorBD.vaciarCampos(clave_TextField, cantidad_TextField);
                } else {
                    JOptionPane.showMessageDialog(null, "No hay suficientes existencias");
                }
            } else {
                JOptionPane.showMessageDialog(null, "No se encontró el producto");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al restar existencias: " + e.toString());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Cantidad inválida");
        }
        
        
    }//GEN-LAST:event_boton_SacarCantidadActionPerformed

    private void boton_ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_ModificarActionPerformed
        // TODO add your handling code here:
        String consulta = "UPDATE Productos SET nombre = ?, precio = ?, proveedor = ?, descripcion = ?, existencias = ? WHERE id = ?";
        try {
            conectorBD.ejecutarConsulta(consulta, nombre_TextField.getText(),precio_TextField.getText(),
            proveedor_TextField.getText(),descripcion_TextArea.getText(),existencias_TextField.getText(),clave_TextField.getText());
            JOptionPane.showMessageDialog(null, "Producto modificado");
        } catch (SQLException e) {
            // TODO Auto-generated catch block
            JOptionPane.showMessageDialog(null, e.toString());
        };
    }//GEN-LAST:event_boton_ModificarActionPerformed

    private void boton_EliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_EliminarProductoActionPerformed
        // TODO add your handling code here:
        String consulta = "DELETE FROM Productos WHERE id = ?";
        try {
            conectorBD.ejecutarConsulta(consulta, clave_TextField.getText());
            JOptionPane.showMessageDialog(null, "Producto eliminado");
        } catch (SQLException e) {
            // TODO Auto-generated catch block
            JOptionPane.showMessageDialog(null, e.toString());
        };
    }//GEN-LAST:event_boton_EliminarProductoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inventario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_AgregarCantidad;
    private javax.swing.JButton boton_Agregar_Producto;
    private javax.swing.JButton boton_Buscar;
    private javax.swing.JButton boton_EliminarProducto;
    private javax.swing.JButton boton_Modificar;
    private javax.swing.JButton boton_SacarCantidad;
    private javax.swing.JTextField cantidad_TextField;
    private javax.swing.JTextField clave_TextField;
    private javax.swing.JTextArea descripcion_TextArea;
    private javax.swing.JTextField existencias_TextField;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nombre_TextField;
    private javax.swing.JTextField precio_TextField;
    private javax.swing.JTextField proveedor_TextField;
    // End of variables declaration//GEN-END:variables
}
